// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/sandeepkv93/googlysync/internal/config"
	"github.com/sandeepkv93/googlysync/internal/logging"
)

// Injectors from wire.go:

func InitializeUI() (*UIApp, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	logger, err := logging.NewLogger(configConfig)
	if err != nil {
		return nil, err
	}
	uiApp, err := NewUIApp(configConfig, logger)
	if err != nil {
		return nil, err
	}
	return uiApp, nil
}
