version: "3"

tasks:
  default:
    desc: List tasks
    cmds:
      - task --list

  bazel:build:
    desc: Build all Bazel targets
    cmds:
      - bazelisk build //...

  bazel:test:
    desc: Run Bazel tests
    cmds:
      - |
        tests=$(bazelisk query 'tests(//...)' 2>/dev/null || true)
        if [ -z "$tests" ]; then
          echo "No Bazel test targets; skipping."
          exit 0
        fi
        bazelisk test $tests

  gazelle:
    desc: Run Gazelle to update BUILD files
    cmds:
      - bazelisk run //:gazelle

  wire:
    desc: Generate Wire DI files
    cmds:
      - go generate -tags=wireinject ./cmd/googlysync

  wire:check:
    desc: Generate Wire files and verify no diffs
    cmds:
      - task wire
      - git diff --exit-code

  buf:gen:
    desc: Generate gRPC code via Buf
    cmds:
      - go run github.com/bufbuild/buf/cmd/buf@v1.34.0 generate

  goose:
    desc: Run Goose migrations via Bazel
    cmds:
      - |
        db=${DB_PATH:-/tmp/googlysync/googlysync.db}
        bazelisk run @com_github_pressly_goose_v3//cmd/goose:goose -- -dir internal/storage/migrations -table goose_db_version sqlite3 "$db" {{.CLI_ARGS}}

  run:daemon:
    desc: Build and run daemon using the built binary
    cmds:
      - task bazel:build
      - bazel-bin/cmd/googlysync/googlysync_/googlysync daemon --config $(pwd)/configs/dev.json

  run:status:
    desc: Build and run status (once) using the built binary
    cmds:
      - task bazel:build
      - bazel-bin/cmd/googlysync/googlysync_/googlysync status --once --socket /tmp/googlysync/daemon.sock

  run:tui:
    desc: Build and run the status TUI using the built binary
    cmds:
      - task bazel:build
      - bazel-bin/cmd/googlysync/googlysync_/googlysync

  clean:
    desc: Clean Bazel outputs
    cmds:
      - bazelisk clean --expunge
