version: "3"

tasks:
  default:
    desc: List tasks
    cmds:
      - task --list

  bazel:build:
    desc: Build all Bazel targets
    cmds:
      - bazelisk build //...

  bazel:test:
    desc: Run Bazel tests
    cmds:
      - |
        tests=$(bazelisk query 'tests(//...)' 2>/dev/null || true)
        if [ -z "$tests" ]; then
          echo "No Bazel test targets; skipping."
          exit 0
        fi
        bazelisk test $tests

  gazelle:
    desc: Run Gazelle to update BUILD files
    cmds:
      - bazelisk run //:gazelle

  wire:
    desc: Generate Wire DI files
    cmds:
      - go generate -tags=wireinject ./cmd/drive-daemon ./cmd/drive-ui ./cmd/drive-fuse

  wire:check:
    desc: Generate Wire files and verify no diffs
    cmds:
      - task wire
      - git diff --exit-code

  goose:
    desc: Run Goose migrations via Bazel
    cmds:
      - |
        db=${DB_PATH:-./var/drive.db}
        bazelisk run @com_github_pressly_goose_v3//cmd/goose:goose -- -dir internal/storage/migrations -table goose_db_version sqlite3 "$db" {{.CLI_ARGS}}

  clean:
    desc: Clean Bazel outputs
    cmds:
      - bazelisk clean --expunge
