version: "3"

tasks:
  default:
    desc: List tasks
    cmds:
      - task --list

  bazel:build:
    desc: Build all Bazel targets
    cmds:
      - bazelisk build //...

  bazel:test:
    desc: Run Bazel tests
    cmds:
      - bazelisk test //...

  gazelle:
    desc: Run Gazelle to update BUILD files
    cmds:
      - bazelisk run //:gazelle

  wire:
    desc: Generate Wire DI files
    cmds:
      - go generate -tags=wireinject ./cmd/drive-daemon ./cmd/drive-ui ./cmd/drive-fuse

  wire:check:
    desc: Generate Wire files and verify no diffs
    cmds:
      - task wire
      - git diff --exit-code

  clean:
    desc: Clean Bazel outputs
    cmds:
      - bazelisk clean --expunge
