// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/sandeepkv93/googlysync/internal/auth"
	"github.com/sandeepkv93/googlysync/internal/config"
	"github.com/sandeepkv93/googlysync/internal/daemon"
	"github.com/sandeepkv93/googlysync/internal/fswatch"
	"github.com/sandeepkv93/googlysync/internal/ipc"
	"github.com/sandeepkv93/googlysync/internal/logging"
	"github.com/sandeepkv93/googlysync/internal/storage"
	"github.com/sandeepkv93/googlysync/internal/sync"
)

// Injectors from wire.go:

func InitializeDaemon(opts config.Options) (*daemon.Daemon, error) {
	configConfig, err := config.NewConfigWithOptions(opts)
	if err != nil {
		return nil, err
	}
	logger, err := logging.NewLogger(configConfig)
	if err != nil {
		return nil, err
	}
	storageStorage, err := storage.NewStorage(configConfig, logger)
	if err != nil {
		return nil, err
	}
	service, err := auth.NewService(logger, storageStorage)
	if err != nil {
		return nil, err
	}
	store := newStatusStore(configConfig)
	queue := newSyncQueue(logger, configConfig)
	engine, err := sync.NewEngine(logger, storageStorage, store, queue)
	if err != nil {
		return nil, err
	}
	watcher, err := fswatch.NewWatcher(logger, configConfig, store)
	if err != nil {
		return nil, err
	}
	server, err := ipc.NewServer(configConfig, logger, store)
	if err != nil {
		return nil, err
	}
	daemonDaemon, err := daemon.NewDaemon(logger, configConfig, storageStorage, service, engine, watcher, server, queue)
	if err != nil {
		return nil, err
	}
	return daemonDaemon, nil
}
