load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "sync",
    srcs = [
        "queue.go",
        "sync.go",
    ],
    importpath = "github.com/sandeepkv93/googlysync/internal/sync",
    visibility = ["//:__subpackages__"],
    deps = [
        "//internal/auth",
        "//internal/config",
        "//internal/driveapi",
        "//internal/fswatch",
        "//internal/status",
        "//internal/storage",
        "@com_github_google_uuid//:uuid",
        "@org_uber_go_zap//:zap",
    ],
)
