// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/sandeepkv93/GooglySync/internal/auth"
	"github.com/sandeepkv93/GooglySync/internal/config"
	"github.com/sandeepkv93/GooglySync/internal/daemon"
	"github.com/sandeepkv93/GooglySync/internal/fswatch"
	"github.com/sandeepkv93/GooglySync/internal/logging"
	"github.com/sandeepkv93/GooglySync/internal/storage"
	"github.com/sandeepkv93/GooglySync/internal/sync"
)

// Injectors from wire.go:

func InitializeDaemon() (*daemon.Daemon, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	logger, err := logging.NewLogger(configConfig)
	if err != nil {
		return nil, err
	}
	storageStorage, err := storage.NewStorage(configConfig, logger)
	if err != nil {
		return nil, err
	}
	service, err := auth.NewService(logger, storageStorage)
	if err != nil {
		return nil, err
	}
	engine, err := sync.NewEngine(logger, storageStorage)
	if err != nil {
		return nil, err
	}
	watcher, err := fswatch.NewWatcher(logger)
	if err != nil {
		return nil, err
	}
	daemonDaemon, err := daemon.NewDaemon(logger, configConfig, storageStorage, service, engine, watcher)
	if err != nil {
		return nil, err
	}
	return daemonDaemon, nil
}
